### ISSUE TITLE
要是面试的200题有答案的话，那就极好了

### ISSUE THREAD

**Issue by Kwum** [tangyouhua/program-resource#7]
大神，有答案吗

**Comment by tangyouhua** [comment]
有，在做，坑一定会填上的，填完再close
不过这中间可能会挖更多的坑:)

**Comment by kungfuq** [comment]
填多少，发多少啊，不用一次性发。。。

**Comment by wuyanru** [comment]
可以大家一起做，这样出答案快一点

**Comment by zhaozhizheng** [comment]
可以大家一起做，这样出答案快一点

**Comment by tangyouhua** [comment]
大部分的答案已经有了，可以关注这个页面 https://github.com/tangyouhua/program-resource/blob/master/program-interview/github-interview-collection.md
